
#include "Diagnose.h"
#include "BSP_48Pin_Pub_L.h"

MOS_ST_PCA_t	MOS_ST_PCA;
//STÒý½ÅÕï¶Ï

void IO_PCA_ST()
{
	
	MOS_ST_State();
	
	//printf("samples:%d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d\n",MOS_ST_PCA.MOS0_ST,MOS_ST_PCA.MOS2_ST,MOS_ST_PCA.MOS4_ST,MOS_ST_PCA.MOS5_ST,MOS_ST_PCA.MOS6_ST,MOS_ST_PCA.MOS7_ST,MOS_ST_PCA.MOS8_ST,MOS_ST_PCA.MOS9_ST,MOS_ST_PCA.MOS10_ST,MOS_ST_PCA.MOS11_ST,MOS_ST_PCA.MOS12_ST,MOS_ST_PCA.MOS13_ST,MOS_ST_PCA.MOS14_ST,MOS_ST_PCA.MOS15_ST,MOS_ST_PCA.MOS16_ST,MOS_ST_PCA.MOS17_ST);
	
}